### ISSUE TITLE
How to map generatedAtTime triple of a feature object from json-ld

### ISSUE THREAD

**Issue by stijnbrysbaert** [stijnbrysbaert/mapper#1]
In order to know what the timestamp of the status of a station is, I would like to pull the generatedAtTime object from the [json-ld](https://datapiloten.be/bluebike/availabilities.geojson).
There is for each feature object a generatedAtTime triple. How can I map this triple with comunica to it's corresponding subject (e.g. http://irail.be/stations/bluebike/Antwerpen-Centraal)

**Comment by stijnbrysbaert** [comment]
[This](http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fdatapiloten.be%2Fbluebike%2Favailabilities.geojson&query=PREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX%20foaf%3A%20%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0APREFIX%20mv%3A%20%20%20%3Chttp%3A%2F%2Fschema.mobivoc.org%2F%3E%0APREFIX%20geo%3A%20%20%3Chttp%3A%2F%2Fwww.w3.org%2F2003%2F01%2Fgeo%2Fwgs84_pos%23%3E%0APREFIX%20locn%3A%20%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Flocn%23%3E%20%0APREFIX%20tn%3A%20%20%20%20%3Chttps%3A%2F%2Fdata.vlaanderen.be%2Fns%2Ftransportnetwerk%23%3E%0APREFIX%20ext%3A%20%20%20%3Chttps%3A%2F%2Fstijnbrysbaert.github.io%2FOSLO-extension%2Fvocabulary.ttl%23%3E%0APREFIX%20geonames%3A%20%3Chttp%3A%2F%2Fwww.geonames.org%2Fontology%23%3E%0APREFIX%20prov%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fprov%23%3E%0A%0ACONSTRUCT%7B%0A%20%20%09%3Fs%20rdf%3Atype%20mv%3AParkingFacility%2C%20tn%3ATransportobject%20.%0A%20%20%09%3Fs2%20prov%3AgeneratedAtTime%20%3Fo%20.%0A%7D%0AWHERE%20%7B%0A%20%20%20%20%3Fs2%20prov%3AgeneratedAtTime%20%3Fo%20.%0A%20%20GRAPH%20%3Fg%20%7B%0A%20%20%20%20%0A%20%20%20%20%3Fs%20rdf%3Atype%20%3Chttp%3A%2F%2Fschema.org%2FParkingFacility%3E%20.%0A%20%20%7D%0A%7D) works, but has the same stations multiple times in the result. Causing +13000 results.

And: how to know which generatedAtTime belongs to which station?

**Comment by pietercolpaert** [comment]
The generated at Time is linked to the graph ?g, so you should do this: http://query.linkeddatafragments.org/#datasources=https%3A%2F%2Fdatapiloten.be%2Fbluebike%2Favailabilities.geojson&query=PREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX%20foaf%3A%20%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0APREFIX%20mv%3A%20%20%20%3Chttp%3A%2F%2Fschema.mobivoc.org%2F%3E%0APREFIX%20geo%3A%20%20%3Chttp%3A%2F%2Fwww.w3.org%2F2003%2F01%2Fgeo%2Fwgs84_pos%23%3E%0APREFIX%20locn%3A%20%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Flocn%23%3E%20%0APREFIX%20tn%3A%20%20%20%20%3Chttps%3A%2F%2Fdata.vlaanderen.be%2Fns%2Ftransportnetwerk%23%3E%0APREFIX%20ext%3A%20%20%20%3Chttps%3A%2F%2Fstijnbrysbaert.github.io%2FOSLO-extension%2Fvocabulary.ttl%23%3E%0APREFIX%20geonames%3A%20%3Chttp%3A%2F%2Fwww.geonames.org%2Fontology%23%3E%0APREFIX%20prov%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fprov%23%3E%0A%0ACONSTRUCT%7B%0A%20%20%09%3Fs%20rdf%3Atype%20mv%3AParkingFacility%2C%20tn%3ATransportobject%20.%0A%20%20%09%3Fg%20prov%3AgeneratedAtTime%20%3Fo%20.%0A%7D%0AWHERE%20%7B%0A%20%20%20%20%3Fg%20prov%3AgeneratedAtTime%20%3Fo%20.%0A%20%20GRAPH%20%3Fg%20%7B%0A%20%20%20%20%0A%20%20%20%20%3Fs%20rdf%3Atype%20%3Chttp%3A%2F%2Fschema.org%2FParkingFacility%3E%20.%0A%20%20%7D%0A%7D

I’ve mapped it this way as this is how the RDF Stream Processing community does it (see for example http://streamreasoning.github.io/RSP-QL/RSP_Requirements_Design_Document/#example-1-rdf-stream-example)

it however makes SPARQL querying really awkward

So I prefer not using named graphs at all, and adding the temporal aspect in the vocabulary itself

So instead of saying the parking facility has 10 free spaces, I’d say: the parking facility → has a status → Status 1, for which Status 1 → says it has free bikes → 5, and Status 1 prov:generatedAtTime "2020-10-..." 

So now in your mapping I would love to see the concept of a parking availability status

**Comment by stijnbrysbaert** [comment]
something like this 6525c8428c07a6c61ea3a265d0b331b32382b487?
output: https://bluebike-mapper.azurewebsites.net/

**Comment by pietercolpaert** [comment]
Yes, https://bluebike-mapper.azurewebsites.net/ looks really good now in my opinion! We need to validate with the Vlaanderen team whether we can use `oslotripsenaanbod:Beschikbaarheid` for this purpose though /cc @GeertThijs

Snippet from the file as it is now:
```turtle
<http://irail.be/stations/bluebike/Brussel-Centraal> a mv:ParkingFacility, tn:Transportobject, adr:AdresseerbaarObject, dc:Location;
    rdfs:label "Brussel-Centraal";
    geonames:nearby <http://irail.be/stations/NMBS/008813003>;
    <https://data.vlaanderen.be/ns/mobiliteit/trips-en-aanbod#Transportobject.beschikbaarheid> _:e_b1;
    locn:geometry _:e_b1.
_:e_b1 a trips:Beschikbaarheid;
    ext:totaalPlaatsen "10"^^xsd:integer;
    ext:voertuigenBeschikbaar "9"^^xsd:integer;
    prov:generatedAtTime "2020-10-20T07:50:09.880Z"^^xsd:date.
```
